export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_WITH_CODES = 'FETCH_COUNTRIES_WITH_CODES';
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_FILTER = 'SET_FILTER';
export const OPEN_DETAILS = 'OPEN_DETAILS';
export const SEARCH_FOR_COUNTRIES = 'SEARCH_FOR_COUNTRIES';
export const SET_LOADING = 'SET_LOADING';
export const START_REQUEST = 'START_REQUEST';
export const REQUEST_FAILED = 'REQUEST_FAILED';


