export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_WITH_CODES = 'FETCH_COUNTRIES_WITH_CODES';
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_FILTER = 'SET_FILTER';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const OPEN_DETAILS = 'OPEN_DETAILS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_ALL_COUNTRIES = 'SET_ALL_COUNTRIES';
export const SET_LOADING = 'SET_LOADING';
export const START_REQUEST = 'START_REQUEST';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const LIGHT_THEME = 'light';
export const DARK_THEME = 'dark';



